// 오사카·교토 2026.10.8~13 — 일정 데이터 (정본: 여행계획_작업본.md)
// status: ok=확정 / cand=후보 / need=예약필요
const P = 'assets/';

window.TRIP_DAYS = [
{
  id: 'd1', date: '10/8', dow: '목', city: 'osaka', short: '도착 · 쇼핑 · 야경',
  title: '도착하자마자, 신사이바시부터 하루카스 야경까지',
  intro: '비행기에서 내리면 곧바로 라피트를 타고 난바로 가자. 호텔에 짐만 내려놓고 16시부터 걷기 시작하면, 해 질 무렵엔 도톤보리 네온 아래 서 있을 거야. 하루의 끝은 300m 위에서 오사카 야경으로.',
  cautions: [
    '아베노 하루카스 킨테츠 백화점은 전관 20:00 마감 → 20시 전에 덴노지 도착이 핵심 (전망대는 22:00, 최종입장 21:30)',
    '도톤보리→신세카이 도보(약 30분)는 백화점 쇼핑과 양자택일 — 지하철 7분으로 가면 백화점이 살아남',
    '매장 정확한 위치·영업시간은 구글맵 최종 확인 (프라이탁·킨달·아린지는 아메무라·호리에 쪽으로 살짝 빠짐)',
    '센니치마에 도구야스지 상점가는 이 동선에 시간이 안 나와 미배치 (상점가 자체도 18~19시 마감)',
  ],
  segments: [
    { id: 'all', label: '전체 동선', type: 'img', src: P + 'map-d1-all.jpg', w: 1614, h: 1726 },
    { id: 'shin', label: '신사이바시 · 도톤보리', type: 'img', src: P + 'map-d1-shinsaibashi.jpg', w: 963, h: 1747 },
    { id: 'ten', label: '덴노지 · 신세카이', type: 'img', src: P + 'map-d1-tennoji.jpg', w: 1884, h: 1446 },
  ],
  stops: [
    { id: 'kix', name: '간사이공항 도착', time: '14:30', status: 'ok', photo: P + 'plane.jpg',
      memo: '부산 13:00 이륙, 14:30 착륙. 입국심사·수하물까지 40분쯤 잡았어. 여기서부터가 우리 여행 시작이야.',
      addr: 'Kansai International Airport (KIX)' },
    { id: 'rapit', name: '라피트 → 난카이난바', time: '15:10', status: 'ok', photo: P + 'rapit.jpg', via: '입국 후 바로 탑승',
      memo: '파란 철가면 같은 특급열차. 난바까지 약 40분. 창밖 보면서 잠깐 숨 고르자.',
      addr: '난카이 라피트 KIX → 난카이난바 (레귤러 ¥1,490 / 관공토쿠와리 할인권 ¥1,350)', pos: { all: [560, 300] } },
    { id: 'hotel', name: '구로몬 크리스탈 호텔 체크인', time: '16:00', status: 'ok', photo: P + 'kuromon-hotel.jpg', via: '도보 약 8분',
      memo: '3일 동안 우리 집. 구로몬시장 바로 앞이라 아침 산책도, 야식도 쉬워. 짐만 두고 바로 나가자.',
      addr: '오사카 난바 · 구로몬 (닛폰바시역 인근)', pos: { all: [975, 125] } },
    { id: 'street', name: '신사이바시스지 상점가 진입', time: '16:30', status: 'ok', photo: P + 'shop-street.jpg', via: '도보 북상 약 12분',
      memo: '북쪽에서 남쪽으로 내려오며 쇼핑 시작. 아케이드라 비가 와도 괜찮아.',
      addr: '신사이바시스지 상점가 (북쪽 입구)', pos: { shin: [430, 70] } },
    { id: 'uniqlo', name: '유니클로 신사이바시점', time: '16:35', status: 'ok', photo: P + 'shop-uniqlo.jpg', via: '도보 2분',
      memo: '오사카 로컬 콜라보 UT 한정 티셔츠가 여기 있어. 커플로 하나씩?',
      addr: '미도스지 · 신사이바시역 바로', pos: { shin: [190, 140] } },
    { id: 'asics', name: '아식스', time: '16:55', status: 'ok', photo: P + 'shop-asics.jpg', via: '도보 1분',
      memo: '유니클로에서 우나기다니미나미도리로 1분. 편한 신발은 10/11 교토 도보 데이 대비이기도 해.',
      addr: '우나기다니미나미도리', pos: { shin: [300, 190] } },
    { id: 'cdg', name: '꼼데가르송 (+베이프)', time: '17:10', status: 'ok', photo: P + 'shop-cdg.jpg', via: '도보 3분',
      memo: '하트 로고 플레이 라인. 파르코·다이마루 쪽.',
      addr: '신사이바시 파르코 / 다이마루', pos: { shin: [285, 330] } },
    { id: 'freitag', name: '프라이탁', time: '17:30', status: 'ok', photo: P + 'shop-freitag.jpg', via: '도보 8분 (아메무라 방향)',
      memo: '오사카 유일 매장. 트럭 방수포로 만든 가방, 세상에 하나뿐인 패턴 고르는 재미.',
      addr: '아메리카무라 · 호리에 방향 (위치 구글맵 확인)', pos: { shin: [70, 560] } },
    { id: 'kindal', name: '킨달 (Kindal)', time: '17:45', status: 'ok', photo: P + 'shop-kindal.jpg', via: '도보 3분',
      memo: '중고 명품·아메카지 컨디션이 좋은 편집샵. 천천히 뒤져보자.',
      addr: '아메리카무라 · 호리에', pos: { shin: [70, 760] } },
    { id: 'second', name: '2nd STREET 신사이바시점', time: '18:00', status: 'ok', photo: P + 'shop-2nd.jpg', via: '도보 6분',
      memo: '세컨핸즈. 상점가 본류로 다시 복귀.',
      addr: '신사이바시스지 상점가', pos: { shin: [470, 860] } },
    { id: 'billys', name: '빌리스 / ARANZI ARONZO', time: '18:10', status: 'ok', photo: P + 'shop-billys.jpg', via: '도보 5분',
      memo: '스니커즈 편집샵 빌리스, 그리고 아린지는 우리 기념품용 소품샵. 작은 거 하나 고르자.',
      addr: '아메리카무라 · 호리에', pos: { shin: [90, 980] } },
    { id: 'dessert', name: '디저트 테이크아웃', time: '18:15~18:30', status: 'cand', photo: P + 'alcyon.jpg', via: '도보 ~10분 남하',
      memo: '첫날은 앉지 말고 들고 먹기로. 크레페리 알시온이 유력한데, 아래 후보 중에 골라줘.',
      addr: '난바역 인근 (알시온은 난바역 182m)', pos: { shin: [430, 1400] },
      nearby: [
        { name: '크레페리 알시온', type: '디저트', note: '타베로그 3.72 · 이 동네 최고 평점대 · ★유력', at: { shin: [330, 1560] } },
        { name: '리쿠로 오지상 치즈케이크', type: '디저트', note: '3.51 · 갓 구운 치즈케이크, 동선 바로 위', at: { shin: [250, 1500] } },
        { name: 'PANAME CREPES DE PARIS', type: '디저트', note: '3.50 · 신사이바시역 144m, 쇼핑 동선 한복판', at: { shin: [230, 100] } },
        { name: '홋쿄쿠(北極) 난바본점', type: '디저트', note: '3.62 · 아이스캔디·타이야키', at: { shin: [200, 1600] } },
        { name: 'GUFO', type: '디저트', note: '3.64 · 소프트아이스크림 (요츠바시)' },
        { name: '교쿠세이야', type: '디저트', note: '3.77 · 화과자, 호텔 코앞 — 야식용으로도' },
      ] },
    { id: 'dotonbori', name: '도톤보리 · 글리코 간판', time: '18:30~18:50', status: 'ok', photo: P + 'glico.jpg', via: '도보 5분',
      memo: '에비스바시 위에서 글리코 아저씨랑 같은 포즈로 한 장. 해가 막 지고 네온이 켜지는 시간이야.',
      addr: '에비스바시 · 도톤보리', pos: { shin: [340, 1240] } },
    { id: 'namba', name: '난바역 → 덴노지역', time: '18:50~19:05', status: 'ok', via: '도보 5분',
      memo: '미도스지선으로 7분. 여기서 지하철을 타야 백화점 20시 마감을 맞출 수 있어.',
      addr: '미도스지선 난바 → 덴노지', pos: { shin: [185, 1640], all: [470, 650] } },
    { id: 'kintetsu', name: '킨테츠 백화점 (하루카스) + 덴노지 미오', time: '19:05~20:00', status: 'ok', photo: P + 'shop-kintetsu.jpg', via: '미도스지선 7분',
      hours: '킨테츠 백화점 전관 20:00 마감 (B2 식당가 22:00 / 12~14F 다이닝 23:00) · 미오는 통상 ~21:00',
      memo: '게스트 쿠폰 5% 할인 챌길 것. 미오엔 빔즈·저널스탠다드 같은 편집샵. 55분이라 짧지만 밀도 있게.',
      addr: '아베노 하루카스 · 덴노지역 직결', pos: { ten: [1440, 1250], all: [1230, 1560] },
      nearby: [ { name: '덴노지 미오', type: '쇼핑', note: '빔즈·저널스탠다드 등 편집샵', at: { ten: [1620, 1190] } } ] },
    { id: 'dinner1', name: '저녁 (후보 중 선택)', time: '20:00~21:00', status: 'cand', photo: P + 'daruma.jpg', via: '도보 10분 / 택시',
      memo: '아직 안 정했어. 신세카이 쿠시카츠로 오사카스럽게 갈지, 하루카스 위층 다이닝에서 편하게 갈지 — 같이 고르자.',
      addr: '신세카이 또는 하루카스 12~14F', pos: { ten: [400, 340] },
      nearby: [
        { name: '다루마 신세카이 총본점', type: '식사', note: '쿠시카츠 · 3.45 · 11:00~22:30 (LO 22:00) · 20시 저녁에 시간 딱', at: { ten: [400, 340] } },
        { name: '하루카스 다이닝 12~14F', type: '식사', note: '~23:00 · 야경 보고 바로 위층에서 해결', at: { ten: [1400, 1300] } },
        { name: '야에카츠(八重勝)', type: '식사', note: '쿠시카츠 노포 · 영업시간 확인 필요, 줄 서야 함', at: { ten: [430, 420] } },
        { name: '모츠히코 (신사이바시)', type: '식사', note: '모츠나베·스키야키 · 24시까지 · 넷 예약 가능 · 동선 밖' },
        { name: '호타루 (히가시신사이바시)', type: '식사', note: '샤부샤부·스키야키 ¥2,000~2,999 · 호텔 도보권' },
      ] },
    { id: 'harukas', name: '아베노 하루카스 300 야경', time: '21:00~22:00', status: 'need', photo: P + 'harukas-night.jpg', via: '도보 10분',
      hours: '09:00~22:00 · 최종입장 21:30',
      memo: '일본에서 가장 높은 전망대 중 하나. 오사카 첫날 밤을 여기서 내려다보자. 사전예약 권장 — 조이패스에 포함되면 교환 방식 확인.',
      addr: '아베노 하루카스 60F', pos: { ten: [1380, 1310], all: [1250, 1600] } },
    { id: 'tsutenkaku', name: '츠텐카쿠 야경 산책 → 호텔', time: '22:00~', status: 'cand', photo: P + 'shinsekai.jpg', via: '도보 15분',
      memo: '컨디션 보고 생략 가능. 힘들면 그냥 택시 타고 호텔 가서 쉬자. 내일은 USJ니까.',
      addr: '신세카이 · 츠텐카쿠', pos: { ten: [480, 240], all: [830, 1130] } },
  ],
},
{
  id: 'd2', date: '10/9', dow: '금', city: 'osaka', short: 'USJ 하루 통으로',
  title: '너의 첫 유니버설, 하루를 통째로',
  intro: '아침은 서두르지 않아. 밖에서 든든하게 먹고 13시쯤 들어가서, 해리포터 낮 → 닌텐도 월드 밤 순서로. 익스프레스 7 C슬롯 덕분에 줄은 거의 안 서. 20시에 나와서 난바에서 늦은 저녁.',
  cautions: [
    '10/9 USJ 개장·폐장 시간 미확인 — 공식 캘린더에서 직접 확인 필요',
    '슈퍼 닌텐도 월드는 정리권/확약권 없으면 못 들어감 → 익스프레스 7(마리오카트·요시 포함)으로 확약권 확보',
    '할로윈 호러 나이츠 기간(9/11~11/8). 20:00 이탈이면 야간 이벤트는 거의 못 봄 — 끝까지 보려면 22:30쯤 난바 저녁으로 변경',
    '10/10~12 3연휴 직전 금요일 — 생각보다 붐빌 수 있음',
  ],
  segments: [
    { id: 'route', label: '호텔 → USJ 이동', type: 'img', src: P + 'map-d2-usj.jpg', w: 2424, h: 1194 },
    { id: 'park', label: '파크 안 흐름', type: 'img', src: P + 'map-d2-park.jpg', w: 1332, h: 1380 }
  ],
  stops: [
    { id: 'wake', name: '느긋한 아침', time: '09:30~10:30', status: 'ok', photo: P + 'kuromon-room.jpg',
      memo: '오픈런 안 해. 푹 자고 여유롭게 준비하자. 파크 안엔 먹을 게 별로 없어서 밥은 밖에서 해결.',
      addr: '구로몬 크리스탈 호텔', pos: { route: [2255, 885] } },
    { id: 'brunch', name: '오픈런 식사', time: '11:00~12:00', status: 'cand', photo: P + 'newbabe.jpg', via: '도보 15분 (홋쿄쿠세이 기준)',
      memo: '세 후보 중 하나. 오므라이스 원조집이냐, 구글 4.6 돈가스냐, 1시간 줄 서는 라멘이냐 — 네가 골라.',
      addr: '신사이바시 또는 나카츠·토요사키', pos: { route: [2000, 620] },
      nearby: [
        { name: '홋쿄쿠세이(北極星) 신사이바시 본점', type: '식사', note: '오므라이스 발상지(1922) · 11:00~21:30 · 호텔 도보 15분', at: { route: [2000, 620] } },
        { name: '뉴베이브(ニューベイブ) 토요사키', type: '식사', note: '돈가스 · 구글 4.6 · 11:00~15:00 · 우메다 북쪽, JR 오사카역→유메사키선 동선' },
        { name: '무기토 멘스케 나카츠점', type: '식사', note: '라멘 · 점심만 11:00~15:30, 화요일 휴무(10/9 금 영업) · 1시간 웨이팅 · 뉴베이브와 같은 동네' },
        { name: '멘노요우지', type: '식사', note: '라멘 · 닛폰바시 496m 호텔 도보권 · 영업시간 확인 필요', at: { route: [2180, 930] } },
      ] },
    { id: 'namba2', name: '오사카난바역 (한신난바선)', time: '12:00', status: 'ok', via: '도보 10분',
      memo: '한신난바선 타고 니시쿠조까지 8분.', addr: '오사카난바역', pos: { route: [1950, 835] } },
    { id: 'nishikujo', name: '니시쿠조 환승', time: '', status: 'ok', via: '한신난바선 8분',
      memo: 'JR 유메사키선으로 갈아타면 5분 뒤 유니버설시티. 전철만 25분, 도보 포함 30~35분.', addr: '니시쿠조역', pos: { route: [1005, 315] } },
    { id: 'usj', name: '유니버설시티역 · 입장', time: '12:45~13:00', status: 'ok', photo: P + 'usj-globe.jpg', via: 'JR 유메사키선 5분',
      hours: '10/9 운영시간 미확인 — 공식 캘린더 확인 필요',
      memo: '1일권 + 익스프레스 7 + 파워업밴드. 글로브 앞에서 첫 사진 찍고 들어가자.',
      addr: '유니버설 스튜디오 재팬', pos: { route: [200, 830], park: [290, 1150] } },
    { id: 'early', name: '파크 초반 · 대기 짧은 곳부터', time: '13:00~14:20', status: 'ok', photo: P + 'usj-halloween.jpg', via: '도보',
      memo: '미니언, 쥬라기 등 대기 짧은 어트랙션. 할로윈 장식도 이때 구경.', addr: '미니언 파크 · 쥬라기 파크', pos: { park: [600, 180] } },
    { id: 'hippo', name: '플라이트 오브 더 히포그리프', time: '14:20~14:50', status: 'ok', photo: P + 'usj-potter.jpg', via: '도보',
      memo: '익스프레스 C슬롯 첫 번째. 호그와트 성을 배경으로 날아.', addr: '위저딩 월드', pos: { park: [930, 1210] } },
    { id: 'hogsmeade', name: '호그스미드 · 버터맥주 · 퍼레이드', time: '15:00~18:00', status: 'ok', via: '도보',
      memo: '버터맥주 한 잔씩 들고 천천히. 나머지 에리어도 이 시간에.', addr: '위저딩 월드 · 파크 전역', pos: { park: [720, 1300] } },
    { id: 'snw', name: '슈퍼 닌텐도 월드', time: '18:10~19:40', status: 'ok', photo: P + 'usj-nintendo.jpg', via: '도보',
      hours: '마리오카트 18:10~18:40 → 요시 어드벤처 18:40~19:10 → 동키콩 19:10~19:40',
      memo: '해 진 뒤 조명 켜진 닌텐도 월드가 제일 예뻐. 파워업밴드로 블록 치기·열쇠 챌린지도 같이.',
      addr: '슈퍼 닌텐도 월드 (확약권 입장)', pos: { park: [1180, 1120] } },
    { id: 'leave', name: '굿즈샵 · 파크 출발', time: '19:40~20:15', status: 'ok', via: '도보',
      memo: '기념품 하나씩 고르고 20시엔 나가자. 유니버설시티역에서 온 길 그대로.', addr: '유니버설시티역', pos: { park: [380, 1040] } },
    { id: 'dinner2', name: '난바 늦은 저녁', time: '21:00', status: 'cand', photo: P + 'motsuhiko.jpg', via: 'JR + 한신난바선 약 35분',
      memo: '하루 종일 걸었으니 따뜻한 국물. 모츠히코는 24시까지 하고 넷 예약도 돼서 제일 안전한 카드야.',
      addr: '신사이바시 · 닛폰바시 일대', pos: { route: [2080, 760] },
      nearby: [
        { name: '모츠히코 (もつ彦) 신사이바시', type: '식사', note: '모츠나베·스키야키 · 24시까지 · 넷 예약 가능 · 신사이바시역 6분', at: { route: [2080, 700] } },
        { name: '호타루 (ほたる)', type: '식사', note: '샤부샤부·스키야키 ¥2,000~2,999 · 영업시간 확인 필요', at: { route: [2150, 780] } },
        { name: '멘노요우지', type: '식사', note: '라멘 · 호텔 도보권 · 간단하게 딱', at: { route: [2180, 930] } },
        { name: '후쿠타로 본점', type: '식사', note: '오코노미야키 · 3.72 · 킨테츠닛폰바시 202m · 확인 필요' },
        { name: '사카나테츠', type: '식사', note: '이자카야 · 술 한잔 곁들이려면' },
      ] },
  ],
},
{
  id: 'd3', date: '10/10', dow: '토', city: 'osaka', short: '힐링 → 교토',
  title: '오사카 마지막 날은 천천히, 밤엔 기온 돌길',
  intro: '고베 당일치기는 접었어. 대신 구로몬시장 아침, 강변 커피, 발마사지, 그리고 16시 스시. 저녁엔 교토로 넘어가서 등롱 켜진 기온을 걷자. 내일 하루 종일 걸을 거라 오늘 발을 아껴두는 날이기도 해.',
  cautions: [
    '구로몬시장 점포 대부분 09:00 오픈 → 아침은 09:00부터',
    '기온 ≠ 청수사. 청수사는 10/10 밤에 못 들어감 (야간 특별 배관은 11/21~30) → 야간엔 기온 산책만',
    '이자카야 라스트오더 대부분 22:00 → 저녁을 먼저 먹고(19:00) 산책(20:30~22:00), 마무리 한잔 순서 권장',
    '하나미코지 사유지 구역은 사진 촬영 금지 (과태료) · 게이샤 촬영 금지',
    '코코네 마사지 예약 미완료',
  ],
  segments: [
    { id: 'osa', label: '오사카 낮 동선', type: 'img', src: P + 'map-d3-osaka.jpg', w: 1203, h: 1786 },
    { id: 'gion', label: '기온 야간 산책', type: 'img', src: P + 'map-d3-gion.jpg', w: 1457, h: 1642 },
    { id: 'kdt', label: '호텔 → 기온', type: 'img', src: P + 'map-d3-hotel-gion.jpg', w: 2156, h: 1406 },
  ],
  stops: [
    { id: 'kuromon', name: '구로몬시장 아침 — 카이센동', time: '09:00~09:45', status: 'ok', photo: P + 'kuromon-market.jpg',
      hours: '점포 대부분 09:00 오픈 (예: 마구로야 쿠로긴 09:00~21:00)',
      memo: '호텔 앞이 시장이야. 참치 전문 마구로야 쿠로긴 같은 곳에서 아침 카이센동. 현금 챙기자.',
      addr: '구로몬시장 (호텔 앞)', pos: { osa: [900, 1735] } },
    { id: 'checkout', name: '체크아웃 → 오사카역 코인로커', time: '10:00~10:30', status: 'ok', via: '미도스지선 약 20분',
      memo: '저녁에 교토행 JR을 오사카역에서 타니까 짐은 처음부터 여기에. 하루가 가벼워져.',
      addr: 'JR 오사카역 코인로커', pos: { osa: [500, 195] } },
    { id: 'brooklyn', name: '브루클린 로스팅 컴퍼니 기타하마', time: '11:00~12:00', status: 'ok', photo: P + 'brooklyn.jpg', via: '요도야바시 경유 5분',
      hours: '토·일 8:00~19:00', memo: '강변 테라스에서 커피 한 잔. 게이한 기타하마역 29번 출구 1분.',
      addr: '주오구 기타하마 1-1-9', pos: { osa: [960, 600] } },
    { id: 'nakanoshima', name: '나카노시마 강변 산책 + 가벼운 점심', time: '12:00~13:00', status: 'ok', via: '도보',
      memo: '16시에 스시가 있으니 점심은 가볍게. 강 따라 걷다가 마음에 드는 곳에서.',
      addr: '나카노시마', pos: { osa: [700, 600] } },
    { id: 'cocone', name: '코코네(COCONE) 발마사지', time: '13:45~15:15', status: 'need', photo: P + 'cocone.jpg', via: '기타하마 → 신사이바시 약 10분',
      hours: '10:00~23:00 연중무휴 · ☎06-6210-4252 · 온라인·LINE·전화 예약',
      memo: '페어 힐링코스 2인 ¥13,000. 내일 은각사~철학의 길~니시키시장 도보 데이 전에 발 관리. 예약은 아직 안 했어.',
      addr: '주오구 신사이바시스지 1-3-13 차차빌딩 4F · 신사이바시역 5번 출구 도보 3분', pos: { osa: [715, 1355] } },
    { id: 'sushi', name: '스시 나카미세', time: '16:00', status: 'ok', photo: P + 'sushi-nakamise.jpg', via: '미도스지선 2정거장 약 15분',
      memo: '예약 확정. 이번 여행에서 제일 기대되는 한 끼 중 하나. 여유 있으면 한큐그랜드빌딩 1F 그르니에 브륄레 밀푀유도 테이크아웃.',
      addr: '우메다', pos: { osa: [640, 150] },
      nearby: [ { name: '그르니에(grenier) 우메다 한큐그랜드빌딩점', type: '디저트', note: '크림브륄레 밀푀유 테이크아웃 전용 · 10:00~20:00', at: { osa: [590, 120] } } ] },
    { id: 'jr', name: 'JR 신쾌속 → 교토', time: '17:30', status: 'ok', via: '오사카역에서 짐 찾기',
      memo: '29분이면 교토. 창밖이 어두워지는 걸 보며 도시가 바뀌는 느낌을 즐기자.', addr: 'JR 오사카 → 교토 (¥580)', pos: { osa: [470, 220] } },
    { id: 'kiori', name: '키오리 이그제큐티브 무로마치 체크인', time: '18:30', status: 'ok', photo: P + 'kiori-ext.jpg',
      memo: '교토 2박. 시조 카라스마 남쭉, 기온까지 도보 15~20분. 내일 저녁 카네코도 여기서 5분 거리야.', addr: 'KIORI Exec Muromachi · 577 Takatsujicho, Shimogyo Ward, Kyoto 600-8434', ll: [34.9995, 135.7585], pos: { kdt: [105, 1075], gion: [40, 1080] } },
    { id: 'terayama', name: '저녁 — 사케도코로 테라야마', time: '19:00', status: 'cand', via: '도보 약 10분',
      hours: '17:00~23:00 (LO 22:00) · 목요일 휴무 (10/10 토 영업)',
      memo: '오반자이랑 사케. 산책 전에 저녁을 먼저 먹는 순서로 가자 — LO 22시라 그래야 여유가 생겨. 가볍게 가려면 아래 대안도.',
      addr: '시모교구 다비야초 317-11', ll: [35.0032, 135.7676], pos: { kdt: [900, 900], gion: [300, 1230] },
      nearby: [
        { name: '타치노미 토리즈키', type: '식사', note: '서서 마시는 야키토리 ¥2,000~2,999 · 스시 먹은 뒤 가볍게' },
        { name: '쿠치바시 모던', type: '식사', note: '야키토리 ¥6,000~7,999 · 카라스마역 321m' },
        { name: '바지 토후', type: '식사', note: '교토다운 두부 요리 ¥3,000~3,999' },
      ] },
    { id: 'shijo', name: '시조대교 (가모강)', time: '20:30', status: 'ok', photo: 'https://commons.wikimedia.org/wiki/Special:FilePath/Kyoto_Gion_At_Night_(135528933).jpeg?width=900', via: '도보 5분',
      memo: '강 건너며 야경. 여기서부터 기온이야.', addr: '시조대교', ll: [35.0038, 135.7716], pos: { kdt: [1150, 720], gion: [700, 1085] } },
    { id: 'shirakawa', name: '시라카와 미나미도리', time: '', status: 'ok', photo: 'https://commons.wikimedia.org/wiki/Special:FilePath/Gion_at_night_(31051047850).jpg?width=900', via: '도보 5분',
      memo: '200m 돌길 + 개천 + 버드나무. 오늘 밤 야경 최고 포인트. 여기서 사진 많이 찍자.', addr: '白川南通 · 중요전통건조물군보존지구', ll: [35.005, 135.7745], pos: { kdt: [1380, 520], gion: [925, 840] } },
    { id: 'tatsumi', name: '타츠미바시 · 타츠미다이묘진', time: '', status: 'ok', photo: 'https://commons.wikimedia.org/wiki/Special:FilePath/Japan_A_Night_in_Gion_(13934184196).jpg?width=900', via: '도보 2분',
      memo: '게이코·마이코들이 모시는 작은 사당.', addr: '巽橋 · 巽大明神', ll: [35.0048, 135.7752], pos: { kdt: [1440, 570], gion: [985, 890] } },
    { id: 'hanamikoji', name: '하나미코지도리', time: '', status: 'ok', photo: 'https://commons.wikimedia.org/wiki/Special:FilePath/JP-Kyoto-Gion-Area-Street-Night-View.jpg?width=900', via: '도보 5분',
      memo: '기온 메인 돌길. 찻집·요정이 늘어서 있어. 사유지 구역엔 촬영 금지 표지판 있으니 카메라는 내려두고 눈으로.', addr: '花見小路通', ll: [35.0028, 135.7752], pos: { kdt: [1400, 920], gion: [960, 1270] } },
    { id: 'yasaka', name: '야사카 신사', time: '~22:00', status: 'ok', photo: 'https://commons.wikimedia.org/wiki/Special:FilePath/Yasaka_Shrine_Kyoto.png?width=900', via: '도보 7분',
      memo: '경내 야간 개방, 등롱 조명. 기온 산책의 종착점. 여유되면 마루야마 공원·야사카탑 조명까지.', addr: '八坂神社', ll: [35.0037, 135.7786], pos: { kdt: [1790, 720], gion: [1420, 1090] } },
    { id: 'bar', name: '마무리 한잔 — Bar Rocking Chair', time: '22:00~', status: 'cand', via: '도보 20분',
      hours: '17:00~25:00 (LO 24:00) · 부정기 휴무 · ☎075-496-8679',
      memo: '교마치야를 개조한 바. 이 지역 바 평점 최상위(3.89). 25시까지라 아무리 늦어도 받아줘.',
      addr: '시모교구 고코마치도리 붓코지사가루 타치바나초 434-2', ll: [35.0005, 135.7666], pos: { kdt: [560, 1000], gion: [180, 1330] } },
  ],
},
{
  id: 'd4', date: '10/11', dow: '일', city: 'kyoto', short: '철학의 길 · 카네코',
  title: '은각사에서 걷기 시작해, 카네코 화로 앞에서 끝나는 날',
  intro: '오늘은 하루 종일 걷는 날이야. 아침 은각사, 철학의 길 카페 호핑, 난젠지 수로각. 오후엔 규카츠와 니시키시장, 하브스 케이크. 저녁은 네가 좋아하는 화로 야키니쿠, 카네코.',
  cautions: [
    '하브스는 19:00 마감이라 저녁엔 못 감 → 16:00으로 배치 (후지다이마루점, 니시키시장 동쪽 끝 바로 옆)',
    '카네코는 17석 · 온라인 예약 불가 · 전화만 → 3연휴 중간이라 반드시 사전 전화 예약 (미완료)',
    '난젠지 유도후·아라시야마는 포기 확정 — 일정에 없음',
    '10/12 공휴일 낀 3연휴 중간 → 교토 인파 예상, 편한 신발 필수',
  ],
  segments: [
    { id: 'kyo', label: '은각사 → 시조 (전체)', type: 'img', src: P + 'map-d4-north.jpg', w: 2266, h: 1805 },
    { id: 'dt', label: '시조 · 가와라마치 (확대)', type: 'img', src: P + 'map-d4-shijo.jpg', w: 1883, h: 1745 },
  ],
  stops: [
    { id: 'ginkaku', name: '은각사 (긴카쿠지)', time: '09:00', status: 'ok', photo: 'https://commons.wikimedia.org/wiki/Special:FilePath/Ginkakuji_Kyoto03-r.jpg?width=900',
      memo: '이끼 정원과 모래 정원. 아침 첫 타임이 가장 조용해.', addr: '銀閣寺', ll: [35.027, 135.7982], pos: { kyo: [2130, 80] } },
    { id: 'path', name: '철학의 길 + 카페 호핑', time: '10:00~11:30', status: 'ok', photo: 'https://commons.wikimedia.org/wiki/Special:FilePath/Tetsugaku-no-michi_-_Philosopher%27s_Walk_-_Kyoto.jpg?width=900', via: '도보',
      memo: '은각사에서 난젠지 쪽으로 약 2km 개천길. 카페가 많으니 눈에 드는 곳에 들어가자. 특정 가게는 아직 안 정했어.',
      addr: '哲学の道', ll: [35.0218, 135.7958], pos: { kyo: [2040, 300] },
      nearby: [ { name: '철학의 길 카페 (미확정)', type: '카페', note: '은각사~난젠지 구간 다수 · 산책 중 마음에 드는 곳으로' } ] },
    { id: 'eikando', name: '에이칸도', time: '11:00~11:40', status: 'ok', via: '도보',
      memo: '단풍 절정은 아니야. 절 자체를 보러 가는 거야.', addr: '永観堂', ll: [35.0147, 135.7947], pos: { kyo: [1990, 500] } },
    { id: 'nanzenji', name: '난젠지 · 수로각', time: '11:45~12:30', status: 'ok', photo: 'https://commons.wikimedia.org/wiki/Special:FilePath/Nanzenji_Suirokaku_Tx-re.jpg?width=900', via: '도보 10분',
      memo: '벽돌 수로각 아래에서 사진. 유도후는 안 먹기로 했으니 점심은 시내에서.', addr: '南禅寺 水路閣', ll: [35.0112, 135.7943], pos: { kyo: [2010, 800] } },
    { id: 'keage', name: '케아게 인클라인', time: '12:40', status: 'ok', via: '도보 5분',
      memo: '옛 철로 위를 걷는 길. 짧게 들렀다가 지하철.', addr: '蹴上インクライン', ll: [35.0107, 135.7888], pos: { kyo: [1645, 845] } },
    { id: 'shiyakusho', name: '교토시야쿠쇼마에역', time: '13:00', status: 'ok', via: '도자이선 약 6분 (케아게 → 교토시야쿠쇼마에)',
      memo: '여기서 시조카와라마치까지 걸어 내려가.', addr: '京都市役所前', ll: [35.0113, 135.7672], pos: { kyo: [340, 835] } },
    { id: 'gyukatsu', name: '규카츠 — 京都勝牛 시조카와라마치점', time: '13:20~14:20', status: 'need', via: '도보 8분',
      hours: '10:30~23:00 (LO 22:30) · 넷 예약 가능 (구루나비 등)',
      memo: '교토 발상 규카츠. 유도후 대신 이걸로 바꿨어. 넷 예약 해두면 대기 없이.',
      addr: '나카교구 코메야초 391 카와라마치 뉴도쿄빌딩 B1 · 한큐 교토카와라마치역 1분', ll: [35.0037, 135.7692], pos: { kyo: [300, 1440], dt: [1700, 340] } },
    { id: 'nishiki', name: '니시키시장', time: '14:30~15:45', status: 'ok', photo: P + 'ref/image42.jpg', via: '도보 5분',
      memo: '교토의 부엌. 꼬치·두부·장아찌 조금씩 집어먹으면서 서쪽으로 걷자.', addr: '錦市場', ll: [35.005, 135.7648], pos: { kyo: [150, 1290], dt: [1250, 125] },
      nearby: [ { name: '니시키시장 카이센동·해산물 노점', type: '식사', note: '미조사 · 원하면 따로 조사' } ] },
    { id: 'harbs', name: 'HARBS 교토 후지다이마루점', time: '16:00~17:00', status: 'ok', via: '도보 3분',
      hours: '백화점 영업시간 (대략 10:30~20:00) · 워크인 · ☎075-213-0641 / 대안: 다이마루 교토점 10:00~19:00 (이트인 LO 18:30)',
      memo: '밀크레페. 원래 19:30이었는데 그 시간엔 닫아서 오후로 옮겼어. 니시키시장 동쪽 끝 바로 옆이라 동선도 딱.',
      addr: '시모교구 시조도리 데라마치 히가시이루 후지다이마루 4F', ll: [35.0037, 135.7664], pos: { kyo: [270, 1330], dt: [1450, 340] } },
    { id: 'kamo', name: '가모강 거리 산책 (일몰)', time: '17:00~18:00', status: 'ok', via: '도보 5분',
      memo: '강변에 나란히 앉아 있는 커플들 사이에 우리도 한 자리.', addr: '鴨川', ll: [35.0022, 135.7716], pos: { kyo: [470, 1500], dt: [1820, 760] } },
    { id: 'kaneko', name: '七輪焼 KANEKO (카네코)', time: '18:30~20:30', status: 'need', via: '도보 15분',
      hours: '15:00~23:00 (LO 22:00) · 부정기 휴무 · 17석 · 온라인 예약 불가, 전화만',
      memo: '시치린 화로에 A4 암소 와규. 교토 저녁 1순위. ¥3,000~4,000. 반드시 전화 예약 — 아직 안 했어.',
      addr: '시모교구 미카게초 460 · 시조역·한큐 카라스마역 도보 6분 · 호텔(키오리)에서 도보 5분',
      nearby: [ { name: '키오리 무로마치 (우리 호텔)', type: '숙소', note: '577 Takatsujicho · 카네코에서 도보 5분, 배불러도 금방', at: { dt: [470, 850] } } ], ll: [35.0012, 135.7595], pos: { dt: [290, 930] } },
    { id: 'kiyamachi', name: '(선택) 기야마치 · 다카세강 산책 or Bar Rocking Chair', time: '21:00~', status: 'cand', via: '도보 15분',
      memo: '다카세강은 기야마치도리 따라 흐르는 운하. 폰토초와 한 블록. 배부르면 그냥 걷기만 해도 좋아.',
      addr: '木屋町 · 高瀬川', ll: [35.0058, 135.7705], pos: { kyo: [430, 1300], dt: [1720, 900] },
      nearby: [
        { name: 'Bar Rocking Chair', type: '바', note: '3.89 · 17:00~25:00 · 교마치야 바', at: { dt: [1430, 950], kyo: [330, 1560] } },
        { name: '살롱 드 테 프랑소와', type: '카페', note: '3.73 · 1930년대 레트로 킷사, 다카세강 옆 (영업시간 확인)', at: { dt: [1690, 430], kyo: [330, 1470] } },
        { name: '스프링밸리 브루어리 교토', type: '바', note: '3.59 · 수제맥주 · 캐주얼' },
      ] },
  ],
},
{
  id: 'd5', date: '10/12', dow: '월·공휴일', city: 'kyoto', short: '우지 · 팀랩 · 온천',
  title: '우지의 말차, 팀랩의 빛, 그리고 온천',
  intro: '아침에 교토역 서쪽 온천 숙소에 짐을 맡기고 우지로. 뵤도인, 화로 구이 점심, 나카무라 토키치 말차. 돌아와서 팀랩 보고 선물 사면, 저녁엔 온천에 몸 담그고 아무것도 안 하는 밤.',
  cautions: [
    '이로리 베니야는 월요일 11:00~15:00 점심만 영업 → 12:00 방문으로 맞춤',
    '나카무라 토키치 뵤도인점은 예약 불가 · 대기 30분 사례 → 대기 시간에 우지강 산책',
    '팀랩 바이오보텍스는 시간지정 예매 (15:00 슬롯)',
    '뵤도인 봉황당 내부 배관은 별도 정리권',
  ],
  segments: [
    { id: 'uji', label: '우지', type: 'img', src: P + 'map-d5-uji.jpg', w: 1614, h: 1163 },
    { id: 'kst', label: '교토역 · 우메코지', type: 'img', src: P + 'map-d5-kyotostation.jpg', w: 1681, h: 1176 },
  ],
  stops: [
    { id: 'co', name: '무로마치 체크아웃 → 교토역', time: '09:30', status: 'ok', photo: P + 'kiori-ext.jpg', via: '지하철 카라스마선 약 5분 (시조 → 교토)',
      memo: '오늘부터 마지막 숙소로 옮겨.', addr: 'KIORI Exec Muromachi · 577 Takatsujicho, Shimogyo Ward', ll: [34.9995, 135.7585], pos: { kst: [800, 35] } },
    { id: 'bag', name: '카덴쇼(우메코지)에 짐 맡기기', time: '09:50', status: 'ok', photo: P + 'kadensho-ext.jpg', via: '도보 약 15분',
      memo: '교토역 서쭉 우메코지. 저녁에 여기서 온천.', addr: '우메코지 카덴쇼', ll: [34.9872, 135.7425], pos: { kst: [230, 940] } },
    { id: 'nara', name: '교토역 → JR 우지역', time: '10:15', status: 'ok', via: '도보 15분',
      memo: '미야코지 쾌속이면 17분, 보통은 27분.', addr: 'JR 나라선 (왕복 ¥480)', ll: [34.9852, 135.76], pos: { kst: [1045, 1020] } },
    { id: 'byodoin', name: '뵤도인 (평등원)', time: '10:45~11:45', status: 'ok', photo: 'https://commons.wikimedia.org/wiki/Special:FilePath/Phoenix_Hall,_Byodo-in,_November_2016_-01.jpg?width=900', via: 'JR 나라선 17~27분 + 도보 10분',
      memo: '10엔 동전에 새겨진 그 봉황당. 연못에 비친 모습이 예뻐. 내부 배관은 별도 정리권.', addr: '平等院', ll: [34.8893, 135.8077], pos: { uji: [1035, 840] } },
    { id: 'omotesando', name: '뵤도인 오모테산도 (차 상점가)', time: '11:45~12:00', status: 'ok', photo: 'https://commons.wikimedia.org/wiki/Special:FilePath/Tea_house_next_to_Uji_bridge.jpg?width=900', via: '도보',
      memo: '말차 가게들 구경하며 점심집까지.', addr: '平等院表参道', ll: [34.8902, 135.8058], pos: { uji: [840, 500] } },
    { id: 'irori', name: '이로리 베니야 점심', time: '12:00~13:15', status: 'need', via: '도보 3분',
      hours: '월요일 11:00~15:00 점심만 영업 · 잇큐 예약 권장',
      memo: '빈초탄 이로리(화로) 구이. 네가 좋아하는 화로 스타일이라 골랐어.', addr: 'JR 우지역 도보 3분 · 뵤도인 403m', ll: [34.8898, 135.803], pos: { uji: [600, 650] } },
    { id: 'tokichi', name: '나카무라 토키치 뵤도인점', time: '13:30~14:30', status: 'ok', via: '도보 5분',
      hours: '10:00~17:00 (카페 LO 16:30) · 예약 불가 · 대기 30분 사례',
      memo: '말차 파르페와 말차 젤리. 줄 서는 동안 우지강·아사기리바시 산책하다 오자.',
      addr: '우지 렌게 5-1 · 게이한 우지역 도보 6분', ll: [34.8886, 135.8086], pos: { uji: [985, 700] },
      nearby: [ { name: '우지강 · 아사기리바시 · 우지가미신사(세계유산)', type: '산책', note: '대기 시간에 소화 가능', at: { uji: [1245, 700] } },
        { name: '나카무라 토키치 본점 (대안)', type: '카페', note: 'JR 우지역 앞 · 뵤도인점이 너무 붐비면 여기로', at: { uji: [350, 810] } } ] },
    { id: 'back', name: 'JR 우지역 → 교토역', time: '14:45', status: 'ok', via: '도보 10분',
      memo: '팀랩 15시 슬롯에 맞춰 복귀.', addr: 'JR 나라선', ll: [34.8905, 135.8005], pos: { uji: [240, 720] } },
    { id: 'teamlab', name: '팀랩 바이오보텍스', time: '15:00~16:30', status: 'ok', via: 'JR 17분 + 도보',
      hours: '시간지정 예매 (15:00) · 결제 완료 2장', memo: '빛 속을 걷는 전시. 사진 많이 남기자.', addr: '교토 (우메코지 공원 인근)', ll: [34.988, 135.7445], pos: { kst: [1330, 1140] } },
    { id: 'gift', name: '선물 쇼핑 — 칼디 → 돈키호테', time: '16:30~17:30', status: 'ok', via: '도보',
      hours: '칼디 커피팜 교토 포르타점 10:00~20:00 (교토역 B2) · 돈키호테 교토 아반티점 9:00~24:00 (하치조구치 바로)',
      memo: '가족·친구들 선물은 오늘 끝내자. 둘 다 교토역 반경 안이라 30분씩이면 충분해.',
      addr: '교토역 포르타 B2 · 아반티', ll: [34.986, 135.7592], pos: { kst: [1090, 1060] },
      nearby: [
        { name: '칼디 커피팜 교토 포르타점', type: '쇼핑', note: '교토역 빌딩 B2 · 10:00~20:00 · 커피·수입식품', at: { kst: [1000, 1040] } },
        { name: '돈키호테 교토 아반티점', type: '쇼핑', note: 'JR 교토역 하치조구치 바로 · 9:00~24:00 · 과자·잡화 대량', at: { kst: [1100, 1150] } },
      ] },
    { id: 'onsen', name: '카덴쇼 체크인 · 온천 · 저녁 · 휴식', time: '17:30~', status: 'ok', photo: P + 'kadensho-onsen.jpg', via: '도보 15분',
      memo: '쇼핑도 외출도 없이 온전히 쉬는 밤. 온천 들어갔다가 저녁 먹고, 일찍 자자.', addr: '우메코지 카덴쇼', ll: [34.9872, 135.7425], pos: { kst: [230, 940] } },
  ],
},
{
  id: 'd6', date: '10/13', dow: '화', city: 'kyoto', short: '온천 아침 · 귀국',
  title: '온천 아침, 교토 라멘 한 그릇, 그리고 집으로',
  intro: '아라시야마는 안 가기로 했어. 아침에 무리하지 말고 온천에서 느긋하게, 교토역 근처 노포 라멘으로 마지막 식사. 12시 하루카 타면 공항까지 80분.',
  cautions: [
    '本家 第一旭은 6:00~25:00, 목요일 휴무 → 화요일 영업, 10:30 방문이 가장 안전',
    '교토 라멘코지(역 빌딩 10F)는 11시 오픈이라 12시 하루카면 빠듯',
    '하루카 12:00편 예약 미완료',
  ],
  segments: [
    { id: 'kst', label: '교토역 · 우메코지', type: 'img', src: P + 'map-d5-kyotostation.jpg', w: 1681, h: 1176 },
    { id: 'go', label: '교토 → 간사이공항 (하루카)', type: 'img', src: P + 'map-d6-haruka.jpg', w: 2721, h: 1653 }
  ],
  stops: [
    { id: 'morning', name: '카덴쇼 온천 아침', time: '08:00~09:00', status: 'ok', photo: P + 'kadensho-onsen.jpg',
      memo: '마지막 아침은 온천에서. 서두르지 않아도 돼.', addr: '우메코지 카덴쇼', ll: [34.9872, 135.7425], pos: { kst: [230, 940] } },
    { id: 'co6', name: '체크아웃', time: '09:30', status: 'ok', memo: '캐리어 여유 공간 확인 — 신사이바시 쇼핑 + 선물 다 들어가야 해.', addr: '우메코지 카덴쇼' },
    { id: 'station', name: '교토역 · 짐 부치기', time: '10:00', status: 'ok', via: '도보 약 15분',
      memo: '하루카 타기 전에 짐 정리.', addr: 'JR 교토역', ll: [34.9858, 135.7588], pos: { kst: [1045, 1020], go: [2405, 250] } },
    { id: 'ramen', name: '本家 第一旭 たかばし본점', time: '10:30~11:30', status: 'ok', via: '도보 5분',
      hours: '6:00~25:00 · 목요일 휴무 · 예약 불가(줄 서기) · ☎075-351-6321',
      memo: '교토 라멘 대표 노포. 새벽부터 열어서 10:30이 가장 안전. 옆집 신푸쿠사이칸(검은 국물)과 라이벌이야.',
      addr: '시모교구 히가시시오코지 무카이하타초 845 · 교토역 도보 5분', ll: [34.9873, 135.7635], pos: { kst: [1250, 950] },
      nearby: [
        { name: '신푸쿠사이칸 본점', type: '식사', note: '검은 국물 교토 라멘 · 다이이치아사히 바로 옆 · 확인 필요', at: { kst: [1290, 950] } },
        { name: '교토 라멘코지', type: '식사', note: '교토역 빌딩 10F · 11:00~ 오픈이라 빠듯' },
      ] },
    { id: 'last', name: '교토역 마지막 쇼핑 · 커피', time: '11:30', status: 'ok', via: '도보 5분',
      memo: '칼디 포르타를 어제 못 갔으면 여기서. 커피 한 잔 들고 플랫폼으로.', addr: '교토역 포르타', ll: [34.9866, 135.7585], pos: { kst: [1045, 990] } },
    { id: 'haruka', name: '하루카 → 간사이공항', time: '12:00 → 13:20', status: 'need', via: '교토역 30번 플랫폼',
      hours: '지정석 ¥3,590 · 예약 미완료', memo: '약 80분. 창가 자리에서 6일을 되감기하며.', addr: 'JR 하루카 교토 → KIX', pos: { go: [1555, 1330] } },
    { id: 'fly', name: '출국 → 부산', time: '15:30 → 17:05', status: 'ok', photo: P + 'plane.jpg',
      memo: '13:20 공항 도착, 수속 후 15:30 출국. 17:05 부산. 다음 여행 얘기하면서 돌아가자.', addr: 'KIX → 부산', pos: { go: [1480, 1400] } },
  ],
},
];
